
import { Product, Customer, Notification, Language } from './types';

export const CATEGORIES = ['Groceries', 'Dairy', 'Snacks', 'Beverages', 'Personal Care', 'Household'];

export const PAKISTAN_BANKS = [
  { id: 'hbl', name: 'HBL', color: 'bg-[#008269]' },
  { id: 'meezan', name: 'Meezan Bank', color: 'bg-[#832625]' },
  { id: 'alfalah', name: 'Bank Alfalah', color: 'bg-[#be1e2d]' },
  { id: 'ubl', name: 'UBL', color: 'bg-[#00529b]' },
  { id: 'mcb', name: 'MCB', color: 'bg-[#1e448b]' },
  { id: 'allied', name: 'Allied Bank', color: 'bg-[#f7931e]' },
];

export const TRANSLATIONS: Record<Language, any> = {
  en: {
    appName: 'Kirana PAK',
    edition: 'Pakistan Edition',
    dashboard: 'Dashboard',
    newBill: 'New Bill (POS)',
    inventory: 'Inventory',
    customers: 'Customers',
    analytics: 'Analytics',
    subscription: 'Subscription',
    storeStatus: 'STORE STATUS',
    premiumPlan: 'Premium Plan',
    freeTrial: '7-Day Free Trial',
    trialActive: 'Trial Active',
    expiresIn: 'Expires in {days} days',
    searchPlaceholder: 'Search products, customers or bills...',
    notifications: 'Notifications',
    markAllRead: 'Mark all as read',
    performance: 'Store Performance',
    welcomeBack: "Welcome back, here's what's happening today.",
    exportReport: 'Export Report',
    newSale: '+ New Sale',
    todaysSales: "Today's Sales",
    totalOrders: 'Total Orders',
    lowStockItems: 'Low Stock Items',
    monthlyRevenue: 'Monthly Revenue',
    salesRevenue: 'Sales Revenue (7 Days)',
    stockAlerts: 'Stock Alerts',
    restock: 'Restock',
    healthyStock: 'All stock levels are healthy',
    viewInventory: 'View Inventory Reports',
    currentOrder: 'Current Order',
    walkIn: 'Walk-in Customer',
    subtotal: 'Subtotal',
    tax: 'Tax',
    total: 'Total',
    processBill: 'PROCESS BILL (PRINT)',
    activePlan: 'Active Plan',
    premiumStore: 'Premium Store',
    perMonth: '₨ 199 / Month',
    nextRenewal: 'Next renewal',
    includedFeatures: 'Included Features',
    paymentMethods: 'Payment Methods',
    connected: 'Connected',
    notConnected: 'Not connected',
    primary: 'PRIMARY',
    connect: 'Connect',
    updatePayment: 'Update Payment Info',
    jazzCash: 'JazzCash',
    easyPaisa: 'Easypaisa',
    nayaPay: 'NayaPay',
    bankAccount: 'Any Bank Gateway',
    buyNow: 'Unlock Premium Now',
    popupTitle: 'Upgrade to Premium',
    popupDesc: 'Keep your store running with unlimited bills, stock alerts, and 24/7 support. Join 500+ successful shop owners.',
    startTrial: 'Continue with Trial',
    selectBank: 'Choose your bank to transfer',
    loginTitle: 'Welcome to Kirana PAK',
    loginDesc: 'Login using your Pakistani mobile number',
    mobileLabel: 'Mobile Number',
    otpLabel: 'Enter 6-Digit OTP',
    sendOTP: 'Send OTP',
    verifyOTP: 'Verify & Login',
    trialExpiredTitle: 'Trial Period Ended',
    trialExpiredDesc: 'Your 7-day free trial has expired. To continue managing your products and sales, please purchase a 1-month Pro subscription.',
    bankInstruction: 'Secure system-to-system payment processing.',
    accountID: 'NayaPay ID (Mobile Number)',
    addProduct: 'Add Product',
    addCustomer: 'Add Customer',
    productName: 'Product Name',
    category: 'Category',
    price: 'Price',
    stock: 'Stock',
    unit: 'Unit',
    save: 'Save',
    cancel: 'Cancel',
    edit: 'Edit',
    delete: 'Delete',
    customerNameLabel: 'Customer Full Name',
    customerPhoneLabel: 'Phone Number (e.g. 03001234567)',
    customerCreditLabel: 'Initial Credit / Udhaar Amount (₨)',
    customerTotalSpentLabel: 'Total Previous Purchases (₨)',
    creditUdhaar: 'Credit / Udhaar',
    customerProfile: 'Customer Profile',
    changePhoto: 'Change Photo',
    profileInstructions: 'The customer can only edit their name and profile picture.',
    viewProfile: 'Profile',
    securePayment: 'Secure Payment Gateway',
    payWith: 'Pay with',
    enterWalletNumber: 'Enter your Wallet Mobile Number',
    paySecurely: 'Pay ₨ 199 Securely',
    processingPayment: 'Processing Payment...',
    paymentSuccess: 'Payment Successful!',
    paymentDesc: 'Your transaction is encrypted and personal details are never exposed.',
    verifyAccount: 'Verify Account',
    accountHolder: 'Account Holder Name',
    amountToPay: 'Enter Amount to Pay',
    confirmPay: 'Confirm & Pay'
  },
  ur: {
    appName: 'کرانہ پاک',
    edition: 'پاکستان ایڈیشن',
    dashboard: 'ڈیش بورڈ',
    newBill: 'نیا بل (POS)',
    inventory: 'انوینٹری',
    customers: 'گاہک',
    analytics: 'تجزیہ',
    subscription: 'سبسکرپشن',
    storeStatus: 'سٹور کی حالت',
    premiumPlan: 'پریمیم پلان',
    freeTrial: '7 دن کا مفت ٹرائل',
    trialActive: 'ٹرائل فعال ہے',
    expiresIn: '{days} دنوں میں ختم ہو رہا ہے',
    searchPlaceholder: 'مصنوعات، گاہک یا بل تلاش کریں...',
    notifications: 'اطلاعات',
    markAllRead: 'سب کو پڑھا ہوا نشان زد کریں',
    performance: 'سٹور کی کارکردگی',
    welcomeBack: 'خوش آمدید، آج کی تفصیلات یہاں ہیں۔',
    exportReport: 'رپورٹ ایکسپورٹ کریں',
    newSale: '+ نئی فروخت',
    todaysSales: 'آج کی فروخت',
    totalOrders: 'کل آرڈرز',
    lowStockItems: 'کم اسٹاک والی اشیاء',
    monthlyRevenue: 'ماہانہ آمدنی',
    salesRevenue: 'فروخت کی آمدنی (7 دن)',
    stockAlerts: 'اسٹاک الرٹس',
    restock: 'اسٹاک بھریں',
    healthyStock: 'اسٹاک کی سطح درست ہے',
    viewInventory: 'انوینٹری رپورٹ دیکھیں',
    currentOrder: 'موجودہ آرڈر',
    walkIn: 'عام گاہک',
    subtotal: 'ذیلی کل',
    tax: 'ٹیکس',
    total: 'کل رقم',
    processBill: 'بل پروسیس کریں (پرنٹ)',
    activePlan: 'فعال پلان',
    premiumStore: 'پریمیم سٹور',
    perMonth: '199 روپے / ماہ',
    nextRenewal: 'اگلی تجدید',
    includedFeatures: 'شامل خصوصیات',
    paymentMethods: 'ادائیگی کے طریقے',
    connected: 'منسلک ہے',
    notConnected: 'منسلک نہیں ہے',
    primary: 'بنیادی',
    connect: 'منسلک کریں',
    updatePayment: 'ادائیگی کی معلومات اپ ڈیٹ کریں',
    jazzCash: 'جاز کیش',
    easyPaisa: 'ایزی پیسہ',
    nayaPay: 'نیا پے',
    bankAccount: 'بینک گیٹ وے',
    buyNow: 'پریمیم ابھی خریدیں',
    popupTitle: 'پریمیم میں اپ گریڈ کریں',
    popupDesc: 'لامحدود بلوں اور اسٹاک الرٹس کے ساتھ اپنے اسٹور کو بہتر بنائیں۔',
    startTrial: 'ٹرائل کے ساتھ جاری رکھیں',
    selectBank: 'منتقلی کے لیے اپنا بینک منتخب کریں',
    loginTitle: 'کرانہ پاک میں خوش آمدید',
    loginDesc: 'پاکستانی موبائل نمبر کے ذریعے لاگ ان کریں',
    mobileLabel: 'موبائل نمبر',
    otpLabel: '6 ہندسوں کا OTP درج کریں',
    sendOTP: 'او ٹی پی بھیجیں',
    verifyOTP: 'تصدیق کریں اور لاگ ان ہوں',
    trialExpiredTitle: 'ٹرائل ختم ہو گیا ہے',
    trialExpiredDesc: 'آپ کا 7 دن کا مفت ٹرائل ختم ہو چکا ہے۔ اسٹور کو دوبارہ چلانے کے لیے پریمیم سبسکرپشن خریدیں۔',
    bankInstruction: 'محفوظ نظام کے ذریعے ادائیگی۔',
    accountID: 'نیا پے اکاؤنٹ ID',
    addProduct: 'پروڈکٹ شامل کریں',
    addCustomer: 'گاہک شامل کریں',
    productName: 'پروڈکٹ کا نام',
    category: 'زمرہ',
    price: 'قیمت',
    stock: 'اسٹاک',
    unit: 'یونٹ',
    save: 'محفوظ کریں',
    cancel: 'منسوخ کریں',
    edit: 'ترمیم',
    delete: 'حذف کریں',
    customerNameLabel: 'گاہک کا مکمل نام',
    customerPhoneLabel: 'فون نمبر (مثال: 03001234567)',
    customerCreditLabel: 'ابتدائی ادھار / کریڈٹ کی رقم (₨)',
    customerTotalSpentLabel: 'کل سابقہ خریداری (₨)',
    creditUdhaar: 'ادھار / کریڈٹ',
    customerProfile: 'گاہک کا پروفائل',
    changePhoto: 'تصویر تبدیل کریں',
    profileInstructions: 'گاہک صرف اپنا نام اور پروفائل تصویر تبدیل کر سکتا ہے۔',
    viewProfile: 'پروفائل',
    securePayment: 'محفوظ پیمنٹ گیٹ وے',
    payWith: 'ادائیگی بذریعہ',
    enterWalletNumber: 'اپنا والٹ موبائل نمبر درج کریں',
    paySecurely: 'محفوظ طریقے سے 199 روپے ادا کریں',
    processingPayment: 'ادائیگی جاری ہے...',
    paymentSuccess: 'ادائیگی کامیاب رہی!',
    paymentDesc: 'آپ کی ادائیگی محفوظ ہے اور ذاتی معلومات ظاہر نہیں کی جاتیں۔',
    verifyAccount: 'اکاؤنٹ کی تصدیق کریں',
    accountHolder: 'اکاؤنٹ ہولڈر کا نام',
    amountToPay: 'ادائیگی کی رقم درج کریں',
    confirmPay: 'تصدیق اور ادائیگی'
  }
};

export const INITIAL_PRODUCTS: Product[] = [
  { id: '1', name: 'Dal Moong 1kg', category: 'Groceries', price: 280, costPrice: 240, stock: 45, minStock: 10, unit: 'kg' },
  { id: '2', name: 'Milk Pak 1L', category: 'Dairy', price: 260, costPrice: 235, stock: 8, minStock: 15, unit: 'pcs' },
  { id: '3', name: 'Tapal Danedar 450g', category: 'Beverages', price: 550, costPrice: 500, stock: 20, minStock: 5, unit: 'pcs' },
  { id: '4', name: 'Sufi Cooking Oil 1L', category: 'Groceries', price: 520, costPrice: 480, stock: 3, minStock: 10, unit: 'pcs' },
  { id: '5', name: 'Lays Masala Big', category: 'Snacks', price: 100, costPrice: 85, stock: 50, minStock: 20, unit: 'pcs' },
];

export const INITIAL_CUSTOMERS: Customer[] = [
  { id: 'c1', name: 'Ahmed Khan', phone: '03001234567', totalSpent: 12500, lastVisit: '2024-05-15', balance: 450 },
  { id: 'c2', name: 'Sara Malik', phone: '03217654321', totalSpent: 4500, lastVisit: '2024-05-10', balance: 0 },
];

export const INITIAL_NOTIFICATIONS: Notification[] = [
  { id: 'n1', type: 'low_stock', message: 'Milk Pak 1L is low on stock (8 remaining)', timestamp: '2 hours ago', isRead: false },
  { id: 'n2', type: 'low_stock', message: 'Sufi Cooking Oil is critically low (3 remaining)', timestamp: '5 hours ago', isRead: false },
  { id: 'n3', type: 'subscription', message: 'Your subscription expires in 5 days', timestamp: '1 day ago', isRead: true },
];

export const MOCK_SALES_DATA = [
  { name: 'Mon', amount: 12000 },
  { name: 'Tue', amount: 15400 },
  { name: 'Wed', amount: 9800 },
  { name: 'Thu', amount: 18200 },
  { name: 'Fri', amount: 22000 },
  { name: 'Sat', amount: 28500 },
  { name: 'Sun', amount: 25000 },
];
